version: '3.3'
services:
  formacaonode:
    container_name: formacaonode
    image: node:lts-alpine3.16
    working_dir: /usr/src/app/Express1
    ports:
      - '9001:3000'
    volumes:
    - ./app:/usr/src/app