version: '3.3'
services:
  formacaonode:
    container_name: formacaonode
    image: node:lts-alpine3.16
    working_dir: /usr/src/app/integracaoMercadoPagoTdd
    env_file:
      - .env
    ports:
      - '9001:3000'
    volumes:
    - ./app:/usr/src/app
    depends_on:
      - mongo
    # entrypoint: npm run dev
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - dbmysql:/var/lib/mysql
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
      MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'
    volumes:
      - dbmongo:/data/db
volumes:
  dbmysql:
    driver: local
  dbmongo:
    driver: local
